#!/bin/bash

# Script which verbosely prints out the permissions of files or folders passed to it
# Ciaron Rider (ciaron.rider+github@gmail.com)

# Usage : perm files

# Bits we are looking for
OTHER_EXECUTE=$((2**0))
  OTHER_WRITE=$((2**1))
   OTHER_READ=$((2**2))
GROUP_EXECUTE=$((2**3))
  GROUP_WRITE=$((2**4))
   GROUP_READ=$((2**5))
OWNER_EXECUTE=$((2**6))
  OWNER_WRITE=$((2**7))
   OWNER_READ=$((2**8))
   STICKY_BIT=$((2**9))
     SGID_BIT=$((2**10))
     SUID_BIT=$((2**11))

# For each file passed in as a command line argument
for file in "$@"
do
   # Make sure the file /folder exists
   if test -e "$file"
   then
      # Find the file's owner
      user=$(stat -c %U "$file")
      
      # Find the group owner of the file
      group=$(stat -c %G "$file")
      
      # Human readable permissions of the file
      permsHuman=$(stat -c %A "$file")
      
      # Decimal version of the permissions
      permsDec=$((8#$(stat -c %a "$file")))

      # Print out filename and human readable permissions
      echo -e "\nFile : $file"
      echo -e "Permissions : $(tput smso)$permsHuman$(tput rmso)"

      # Test if the owner has read access
      if test $((permsDec & OWNER_READ)) -eq $OWNER_READ
      then
         echo -e "$(tput setaf 2)The user $(tput smso)$user$(tput rmso) has read permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)The user $(tput smso)$user$(tput rmso) does not have read permissions on this file$(tput sgr0)"
      fi

      # Test if the owner has write access
      if test $((permsDec & OWNER_WRITE)) -eq $OWNER_WRITE
      then
         echo -e "$(tput setaf 2)The user $(tput smso)$user$(tput rmso) has write permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)The user $(tput smso)$user$(tput rmso) does not have write permissions on this file$(tput sgr0)"
      fi

      # Test if the owner has execute access
      if test $((permsDec & OWNER_EXECUTE)) -eq $OWNER_EXECUTE
      then
         echo -e "$(tput setaf 2)The user $(tput smso)$user$(tput rmso) has execute permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)The user $(tput smso)$user$(tput rmso) does not have execute permissions on this file$(tput sgr0)"
      fi

      # Test if the group users have read access
      if test $((permsDec & GROUP_READ)) -eq $GROUP_READ
      then
         echo -e "$(tput setaf 2)Users in the group $(tput smso)$group$(tput rmso) have read permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)Users in the group $(tput smso)$group$(tput rmso) do not have read permissions on this file$(tput sgr0)"
      fi

      # Test if the group users have write access
      if test $((permsDec & GROUP_WRITE)) -eq $GROUP_WRITE
      then
         echo -e "$(tput setaf 2)Users in the group $(tput smso)$group$(tput rmso) have write permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)Users in the group $(tput smso)$group$(tput rmso) do not have write permissions on this file$(tput sgr0)"
      fi

      # Test if the group users have execute access
      if test $((permsDec & GROUP_EXECUTE)) -eq $GROUP_EXECUTE
      then
         echo -e "$(tput setaf 2)Users in the group $(tput smso)$group$(tput rmso) have execute permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)Users in the group $(tput smso)$group$(tput rmso) do not have execute permissions on this file$(tput sgr0)"
      fi

      # Test if everybody else has read access
      if test $((permsDec & OTHER_READ)) -eq $OTHER_READ
      then
         echo -e "$(tput setaf 2)Other users have read permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)Other users do not have read permissions on this file$(tput sgr0)"
      fi

      # Test if everybody else has write access
      if test $((permsDec & OTHER_WRITE)) -eq $OTHER_WRITE
      then
         echo -e "$(tput setaf 2)Other users have write permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)Other users do not have write permissions on this file$(tput sgr0)"
      fi

      # Test if everybody else has execute access
      if test $((permsDec & OTHER_EXECUTE)) -eq $OTHER_EXECUTE
      then
         echo -e "$(tput setaf 2)Other users have execute permissions on this file$(tput sgr0)"
      else
         echo -e "$(tput setaf 1)Other users do not have execute permissions on this file$(tput sgr0)"
      fi

      # Test if the SUID bit has been set
      if test $((permsDec & SUID_BIT)) -eq $SUID_BIT
      then
         echo -e "$(tput setaf 2)Users executing this file will do so with $(tput smso)$user$(tput rmso) user's privileges$(tput sgr0)"
      fi

      # Test if the SGID bit has been set
      if test $((permsDec & SGID_BIT)) -eq $SGID_BIT
      then
         echo -e "$(tput setaf 2)Users executing this file will do so with $(tput smso)$user$(tput rmso) group's privileges$(tput sgr0)"
      fi

      # Test if the sticky bit has been set
      if test $((permsDec & STICKY_BIT)) -eq $STICKY_BIT
      then
         echo -e "$(tput setaf 2)The sticky bit is set on this file$(tput sgr0)"
      fi
   else # File doesn't exist
      echo -e "$(tput setaf 1)$file does not exist$(tput sgr0)"
   fi
done
